version: '3'

includes:
  base:
    taskfile: ../../base/node/Taskfile.yml
    dir: ./project


tasks:
  start:
    desc: Start the background processor
    cmds:
      - task: base:start

  start:prod:
    desc: Start the background processor in production mode
    deps: [build]
    dir: ./project
    cmds:
      - pnpm run start

  build:
    desc: Build the project
    cmds:
      - task: base:build
