name: poe-accountant

services:
  postgres:
    image: docker.io/postgres:${POSTGRES_VERSION}
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - poe-accountant-postgres-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  valkey:
    image: ghcr.io/valkey-io/valkey:${VALKEY_VERSION}
    container_name: valkey
    ports:
      - "${VALKEY_PORT}:6379"
    command: valkey-server --requirepass "${VALKEY_PASSWORD}"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    
  valkey-proxy:
    image: docker.io/hiett/serverless-redis-http:latest
    container_name: valkey-proxy
    environment:
      SRH_MODE: env
      SRH_TOKEN: ${VALKEY_PASSWORD}
      SRH_CONNECTION_STRING: redis://:${VALKEY_PASSWORD}@valkey:${VALKEY_PORT}
      SRH_PORT: 80
    ports:
      - "${VALKEY_PROXY_PORT}:80"
    depends_on:
      valkey:
        condition: service_healthy
    restart: unless-stopped

  api:
    image: pathofexile.accountant.localhost/api:latest
    container_name: api
    ports:
    - "${API_PORT}:4000"
    environment:
      CLOUDFLARE_HYPERDRIVE_LOCAL_CONNECTION_STRING_HYPERDRIVE: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}
      VALKEY_URL: http://:${VALKEY_PASSWORD}@valkey-proxy:80
      VALKEY_TOKEN: ${VALKEY_PASSWORD}
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID:-minioadmin}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY:-minioadmin}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME:-poe-accountant-assets}
      FRONTEND_URL: http://localhost:${FRONTEND_PORT}
    restart: unless-stopped

  background-processor:
    image: pathofexile.accountant.localhost/background-processor:latest
    container_name: background-processor
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}
      VALKEY_URL: redis://:${VALKEY_PASSWORD}@valkey:${VALKEY_PORT}
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID:-minioadmin}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY:-minioadmin}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME:-poe-accountant-assets}
    depends_on:
      postgres:
        condition: service_healthy
      valkey:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    image: pathofexile.accountant.localhost/frontend:latest
    container_name: frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      NODE_ENV: development
      PORT: ${FRONTEND_PORT}
      VITE_API_BASE_URL: http://localhost:${API_PORT}
    restart: unless-stopped

  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY_ID:-minioadmin}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_ACCESS_KEY:-minioadmin}
    command: server /data --console-address ":9001"
    restart: unless-stopped
    volumes:
      - poe-accountant-minio-data:/data

  create-buckets:
    image: quay.io/minio/mc
    depends_on:
      minio:
        condition: service_started
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 ${S3_ACCESS_KEY_ID:-minioadmin} ${S3_SECRET_ACCESS_KEY:-minioadmin};
      /usr/bin/mc mb --ignore-existing myminio/${S3_BUCKET_NAME:-poe-accountant-assets};
      /usr/bin/mc anonymous set public myminio/${S3_BUCKET_NAME:-poe-accountant-assets};
      exit 0;
      "


networks:
  default:
    name: ${DOCKER_NETWORK}

volumes:
  poe-accountant-postgres-data:
  poe-accountant-minio-data:
