version: '3'

dotenv: ['.env.local', '.env']

includes:
  tf:
    taskfile: ./terraform/Taskfile.yml
    dir: ./terraform
    
  api:
    taskfile: ./projects/api/Taskfile.yml
    dir: ./projects/api
  frontend:
    taskfile: ./projects/frontend/Taskfile.yml
    dir: ./projects/frontend
  common:
    taskfile: ./projects/common/Taskfile.yml
    dir: ./projects/common
  ninja:
    taskfile: ./projects/ninja/Taskfile.yml
    dir: ./projects/ninja-server

tasks:
  install:
    cmds:
      - pnpm install

  start:
    cmds:
      - docker compose up -d

  test:
    cmds:
      - pnpm -r test

  lint:
    cmds:
      - pnpm -r lint

  build:
    deps: [install]
    cmds:
      - pnpm -r build

  docker:build:
    cmds:
      - docker buildx bake --progress=plain

  setup:
    cmds:
      - cp .env.example .env
      - task: install
      - task: build
