version: '3'

dotenv: ['.env.local', '.env']

includes:
  tf:
    taskfile: ./terraform/Taskfile.yml
    dir: ./terraform
    
  api:
    taskfile: ./projects/api/Taskfile.yml
    dir: ./projects/api
  frontend:
    taskfile: ./projects/frontend/Taskfile.yml
    dir: ./projects/frontend
  common:
    taskfile: ./projects/common/Taskfile.yml
    dir: ./projects/common
  ggg:
    taskfile: ./projects/ggg-processor/Taskfile.yml
    dir: ./projects/ggg-processor

tasks:
  install:
    cmds:
      - pnpm install

  start:
    cmds:
      - docker compose up -d

  test:
    cmds:
      - pnpm -r test

  lint:
    cmds:
      - pnpm -r lint

  build:
    deps: [install]
    cmds:
      - pnpm -r build

  docker:build:
    cmds:
      - docker buildx bake --progress=plain

  docker:push:
    vars:
      REGISTRY:
        sh: cd terraform && tofu output -raw registry_endpoint
    cmds:
      - doctl auth init -t {{.TF_VAR_do_token}}
      - doctl registry login
      - REGISTRY="{{.REGISTRY}}" docker buildx bake --push --progress=plain
      - docker buildx imagetools create \
          --tag {{.REGISTRY}}/valkey-proxy:latest \
          hiett/serverless-redis-http:latest

  setup:
    cmds:
      - cp .env.example .env
      - task: install
      - task: build
