version: '3'

includes:
  base:
    taskfile: ../../base/node/Taskfile.yml
    dir: ./project

tasks:
  start:
    desc: Start the API server in development mode
    dir: .
    cmds:
      - task: base:start
