version: '3'

includes:
  base:
    taskfile: ../../base/node/Taskfile.yml
    dir: ./project

tasks:
  start:
    desc: Start the API server in development mode
    dir: .
    cmds:
      - cmd: CLOUDFLARE_HYPERDRIVE_LOCAL_CONNECTION_STRING_HYPERDRIVE=$DATABASE_URL task base:start
