name = "meepen-poe-accountant-api"
main = "src/index.ts"
compatibility_date = "2026-01-18"

compatibility_flags = ["nodejs_compat"]

[vars]
CORS_ORIGIN = "*"
VALKEY_URL = "http://localhost:8079"
VALKEY_TOKEN = "valkey"

# Create this with: wrangler hyperdrive create <NAME> --connection-string="postgres://..."
[[hyperdrive]]
binding = "HYPERDRIVE"
id = "local"
localConnectionString = "postgresql://postgres:postgres@postgres:5432/poe_accountant"
